### ISSUE TITLE
Mapa 

### ISSUE THREAD

**Issue by 0eeixl** [SistemasTecTlaxiaco/actividad-4-mapa-mental-0eeixl#1]
[mapa menta de comu.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-0eeixl/files/9648500/mapa.menta.de.comu.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion por favor...

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/193684759-45bb957b-94db-46d8-8913-77f4474545b6.png)
El mapa debe tener una estructura, se debe hacer nuevamente el mapa

**Comment by gilbertovelasco1** [comment]
Eso lo Iba a calificar usted profe

**Comment by josealfredo79** [comment]
Por favor rehacer su trabajo...

**Comment by 0eeixl** [comment]
[mapa 4.3 comuni.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-0eeixl/files/9718368/mapa.4.3.comuni.pdf)

**Comment by josealfredo79** [comment]
Un mapa mental contiene conectores, imágenes y estructura, este mapa mental no tiene todos los elementos anteriores

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/194155017-fa86275d-5a88-4aa7-b6d8-5aa95dacc6be.png)

**Comment by josealfredo79** [comment]
Favor de mejorar mucho el trabajo para la próxima no se revisa

**Comment by josealfredo79** [comment]
Calificacion 12
